version: '3.7'
services:
  database:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - video
    restart: always
    entrypoint: ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'rs0']

  setup-replicaset:
    image: mongo
    networks:
      - video
    depends_on:
      - database
    restart: 'no'
    entrypoint:
      [
        'bash',
        '-c',
        'sleep 5 && mongosh --host database:27017 --eval "rs.initiate({_id:''rs0'', members: [{_id:0, host: ''database''}]})"',
      ]
  video_api:
    image: node:14.15-alpine
    volumes:
      - ../:/video_api
    working_dir: /video_api
    ports:
      - 3000:3000
      - 9229:9229
    env_file: ../.env
    links:
      - database
    depends_on:
      - database
      - setup-replicaset
    environment:
      - APPLICATION_NAME=video_api
      - PORT=3000
      - MONGO_URI=mongodb://172.17.0.1:27017
      - MONGO_USER=any
      - MONGO_PASSWORD=any
      - MONGO_DB_NAME=videos
      - TZ=America/Sao_Paulo
    command: ash -c "npm install && npm run seeds:clearDb && npm run seeds:generate && npm run dev"
    networks:
      - video
networks:
  video:
    driver: bridge
