version: '3.7'
services:
  database: 
    image: mongo
    networks:
      - video
    ports:
      - 27017:27017
    restart: always
    entrypoint: ['/usr/bin/mongod', '--bind_ip_all']
  video_api:
    image: node:14.15-alpine
    volumes:
      - ../:/video_api
    working_dir: /video_api
    ports:
      -3000:3000
    env_file: ../.env
    links:
      - database
    depends_on:
      - database
    environment:
      - APPLICATION_NAME=video_api
      - PORT=3000
      - MONGO_URI=mongodb://172.17.0.1:27017
      - MONGO_USER=any
      - MONGO_PASSWORD=any
      - MONGO_DB_NAME=video
      - TZ=America/Sao_Paulo
    command: ash -c "npm ci && npm run dev"
    networks:
      - video
networks:
  video:
    driver: bridge